# .gitlab-ci.yml

# Define the stages of the pipeline
stages:
  - test
  - deploy

# Define the job for testing
test:
  stage: test
  image: python:3.9  # Use Python Docker image
  before_script:
    - pip install -r requirements.txt  # Install dependencies
  script:
    - python -m pytest  # Run tests
  artifacts:
    paths:
      - script.log  # Archive log file for reference

# Define the job for deployment (assuming deployment actions here)
deploy:
  stage: deploy
  image: python:3.9  # Use Python Docker image
  before_script:
    - pip install -r requirements.txt  # Install dependencies
  script:
    - python main.py  # Run the Python script
  only:
    - master  # Only deploy on changes to the master branch
